---
- name: Copy mysql dump files to s3
  aws_s3:
    bucket: "{{ item.mysqldump.backup.s3_bucket if (item.mysqldump.backup is defined and item.mysqldump.backup.s3_bucket is defined) else item.mysqldump.s3_bucket }}"
    object: "{{ item.mysqldump.backup.s3_bucket_path if (item.mysqldump.backup is defined and item.mysqldump.backup.s3_bucket_path is defined) else item.mysqldump.s3_bucket_path }}/{{ item.dump_file | basename }}"
    src: "{{ item.dump_file }}"
    mode: put
  loop: "{{ mysql_dbs }}"
#  vars:
#    default_object_name: "{{ item.mysqldump.backup.object_name | d(item.id) }}_{{ ansible_date_time.date }}_{{ ansible_date_time.epoch }}"
