---
- name: Copy mysql dump files to s3
  aws_s3:
    bucket: "{{ item.mysqldump.s3_bucket | d (item.mysqldump.service.backup.s3_bucket) }}"
    object: "{{ item.mysqldump.s3_bucket_path | d (item.mysqldump.service.backup.s3_bucket_path) | dirname }}/{{ default_object_name }}"
    src: "{{ item.
  vars:
    default_object_name: "{{ item.mysqldump.backup.object_name | d(item.id) }}_{{ ansible_date_time.date }}_{{ ansible_date_time.epoch }}"
