---
- name: Generate unqiue file path for dump file 
  set_fact:
    _dump_path: "/tmp/{{ (item.mysqldump.backup.object_name is defined ) | ternary (item.mysqldump.backup.object_name, item.id) }}_{{ ansible_date_time.date }}_{{ ansible_date_time.epoch }}.sql"
  loop: "{{ mysql_dbs }}"
  register: _dump_name_facts

- name: Create new list with dump_file
  set_fact:
    mysql_dbs: "{{ mysql_dbs | d ([]) + [{ 'dump_file': item.ansible_facts._dump_path }] }}"
  loop: _dump_name_facts.results
