---
# tasks file for emorylib_role_mysqldump_restore_via_s3
#
- name: Run logic for mysqldump
  include_tasks:
    name: mysqldump.yml
    apply:
      tags:
        - mysqldump
    tags:
      - mysqldump
