---
- name: "{{ (service_state == 'stopped') | ternary('Stop', 'Start') }} service via systemctl"
  systemd:
    name: "{{ item.mysqldump.service.name }}"
    state: "{{ service_state }}"
  loop: "{{ mysql_dbs }}"
  when: > 
     item.mysqldump.service.name is defined and
     item.mysqldump.service.method != 'service' or
     item.mysqldump.service.method is undefined

- name: "{{ (service_state == 'stopped') | ternary('Stop', 'Start') }} service via /etc/init.d"
  service:
    name: "{{ item.mysqldump.service.name }}"
    state: "{{ service_state }}"
  loop: "{{ mysql_dbs }}"
  when: 
    - item.mysqldump.service.name is defined
    - item.mysqldump.service.method is defined
    - item.mysqldump.service.method == 'service'
