---
- name: {{ (mysql_db_state == 'dump') | ternary('Backup', 'Import') }} mysql database
  mysql_db:
    name: "{{ item.name }}"
    login_host: "{{ item.login_host }}"
    login_user: "{{ item.login_user }}"
    login_password: "{{ item.login_password }}"
    single_transation: "{{ (mysql_db_state == 'dump') | ternary(yes, omit) }}"
    state: "{{ mysql_db_state }}"
    target: "{{ item.dump_file }}"
  loop: "{{ mysql_dbs }}"
